org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=true


## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109


## Mod Properties
mod_id=playingcards
mod_name=Unofficial Playing Cards Mod
mod_license=GPL-3.0
mod_version=2.1.0
mod_group_id=com.ombremoon
mod_authors=Calemi, OmbreMoon
mod_description=Unofficial community fork of Playing Cards by Calemi and OmbreMoon. Adds playing cards, poker chips, and more!
